# Generated by Django 5.1.4 on 2026-05-22 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_lat', models.FloatField()),
                ('current_lon', models.FloatField()),
                ('current_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField()),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_trip_hours', models.FloatField(blank=True, null=True)),
                ('days_required', models.PositiveIntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('current', 'Current Location'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest_30min', '30-Min Rest Break'), ('rest_10hr', '10-Hr Mandatory Rest'), ('rest_34hr', '34-Hr Restart'), ('fuel', 'Fuel Stop')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hrs', models.FloatField()),
                ('miles_from_prev', models.FloatField(default=0)),
                ('activity', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('total_miles', models.FloatField(default=0)),
                ('events', models.JSONField(default=list)),
                ('totals', models.JSONField(default=dict)),
                ('recap', models.JSONField(default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
